import { targets, connect } from "./cdp.mjs";
import fs from "node:fs";
const id = fs.readFileSync("/private/tmp/stash-e2e/extid", "utf8").trim();
const ts = await targets();
const sw = ts.find((t) => t.type === "service_worker" && t.url.startsWith(`chrome-extension://${id}/`));
console.log("service worker:", sw?.url);
const w = await connect(sw.webSocketDebuggerUrl);
await w.eval(`chrome.storage.local.set({ token: "e2e-token" })`);
console.log("ping        ->", await w.eval(`__stash.client.ping().then(r => JSON.stringify(r))`));
const tab = JSON.parse(await w.eval(`chrome.tabs.query({}).then(ts => JSON.stringify(ts.find(t => t.url.startsWith("http://127.0.0.1:8765"))))`));
console.log("test tab    ->", tab.id, tab.url, "|", tab.title);
const click = (info) => w.eval(`__stash.handleMenuClick(${JSON.stringify(info)}, ${JSON.stringify(tab)}).then(r => JSON.stringify(r))`);
console.log("save image  ->", await click({ menuItemId: "stash:inbox", mediaType: "image", srcUrl: "http://127.0.0.1:8765/hero.png", pageUrl: tab.url }));
console.log("save link   ->", await click({ menuItemId: "stash:inbox", linkUrl: "http://127.0.0.1:8765/index.html", pageUrl: tab.url }));
console.log("save page   ->", await click({ menuItemId: "stash:inbox", pageUrl: tab.url }));
console.log("bad token   ->", await w.eval(`chrome.storage.local.set({token:"wrong"}).then(() => __stash.client.ping()).then(() => "unexpected ok", e => e.kind)`));
await w.eval(`chrome.storage.local.set({ token: "e2e-token" })`);
console.log("recent      ->", await w.eval(`chrome.storage.local.get("lastSaved").then(s => JSON.stringify(s.lastSaved.map(x => x.kind + ":" + x.name)))`));
w.close();
